[General]
AppendVideoToSingleInstance=true
LastPlayedFile=file:///home/andrel/Videos/Recordings/2026-03-17 12-45-48.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true
UseSingleInstance=true
