[General]
AppendVideoToSingleInstance=true
LastPlayedFile=file:///run/user/1000/gvfs/smb-share:server=192.168.2.28,share=shared/Videos/Tv/Star Trek - Strange New Worlds/Season 2/Star Trek Strange New Worlds S02E08.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true
UseSingleInstance=true
